# Connection Manager Service Configuration

[service]
port = 5000
host = "0.0.0.0"
debug = false

[network]
# Default connection priorities (lower number = higher priority)
# Connection types: ethernet, wifi, lte
priorities = [
  { type = "ethernet", priority = 1 },
  { type = "wifi", priority = 2 },
  { type = "lte", priority = 3 }
]

# Default WiFi AP settings
[network.ap]
ssid = "ARK-AP"
password = "arkosdrone"